# Generated by Django 4.0 on 2021-12-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_place', models.CharField(max_length=25)),
                ('budget', models.IntegerField(default=10)),
                ('why_this_place', models.TextField(max_length=1000)),
                ('already_visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDestination',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.destination')),
                ('restricted_area', models.BooleanField(default=True)),
            ],
            bases=('places.destination',),
        ),
        migrations.CreateModel(
            name='TouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_tourist_place', models.CharField(max_length=25)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.destination')),
            ],
        ),
    ]
